//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8922
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] _000_lo {
            get {
                object obj = ResourceManager.GetObject("_000_lo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] mainbios {
            get {
                object obj = ResourceManager.GetObject("mainbios", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;mame version=&quot;1&quot;&gt;
        ///  &lt;game name=&quot;forgottn&quot; board=&quot;CPS-1&quot;&gt;
        ///    &lt;parent&gt;&lt;/parent&gt;
        ///    &lt;direction&gt;&lt;/direction&gt;
        ///    &lt;description&gt;Forgotten Worlds (World, newer)&lt;/description&gt;
        ///    &lt;year&gt;1988&lt;/year&gt;
        ///    &lt;manufacturer&gt;Capcom&lt;/manufacturer&gt;
        ///  &lt;/game&gt;
        ///  &lt;game name=&quot;forgottna&quot; board=&quot;CPS-1&quot;&gt;
        ///    &lt;parent&gt;forgottn&lt;/parent&gt;
        ///    &lt;direction&gt;&lt;/direction&gt;
        ///    &lt;description&gt;Forgotten Worlds (World)&lt;/description&gt;
        ///    &lt;year&gt;1988&lt;/year&gt;
        ///    &lt;manufacturer&gt;Capcom&lt;/manufacturer&gt;
        ///  &lt;/game&gt;
        ///  &lt;ga [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mame {
            get {
                return ResourceManager.GetString("mame", resourceCulture);
            }
        }
        
        internal static byte[] mcu {
            get {
                object obj = ResourceManager.GetObject("mcu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pgmaudiobios {
            get {
                object obj = ResourceManager.GetObject("pgmaudiobios", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pgmmainbios {
            get {
                object obj = ResourceManager.GetObject("pgmmainbios", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pgmvideobios {
            get {
                object obj = ResourceManager.GetObject("pgmvideobios", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readme abc.
        /// </summary>
        internal static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
        
        internal static byte[] sfix {
            get {
                object obj = ResourceManager.GetObject("sfix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sm1 {
            get {
                object obj = ResourceManager.GetObject("sm1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
